name: nicomiguelino-hello
base: core22
version: '0.1.0'
summary: GNU Hello, the "hello world" snap
description: |
  GNU hello prints a friendly greeting.
grade: stable
confinement: strict

apps:
  hello:
    command: usr/local/bin/hello
  bash:
    command: usr/local/bin/bash

parts:
  gnu-hello:
    source: http://ftp.gnu.org/gnu/hello/hello-2.10.tar.gz
    plugin: autotools
  gnu-bash:
    source: http://ftp.gnu.org/gnu/bash/bash-5.2.tar.gz
    plugin: autotools
